# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3e937058dbd47fb633e23e68eab54b6f40a24a1ad5f3c1b6ce5a5a91e079a7538835192c78073cf94b3e725fb221af3dd5bdcec5065b2704989e619d3ad75d

test:
  secret_key_base: 8c24d0d22c6fda249140fc7b681a20347725cc71b0185f6ab245c483113ebdc053fc31e25730e2cfa6cc92bb2e9fb6aa4d634bac7ca0bcc30934799fecd840cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
